# Generated by Django 3.0.6 on 2020-05-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_name', models.CharField(max_length=1000)),
                ('new_author', models.CharField(max_length=100)),
                ('new_intro', models.TextField(max_length=300)),
                ('new_des', models.TextField()),
                ('new_count', models.PositiveSmallIntegerField(default=0)),
                ('new_intro_pic', models.ImageField(upload_to='new_pictures')),
            ],
        ),
    ]
